
language: python

python:
  - "2.7"

before_install:
  - chmod +x setup-DEBs.sh
  - sudo ./setup-DEBs.sh

install:
  - chmod +x setup-DEBs.sh
  - sudo ./setup-CGAT.sh

script: 
  - cgat --help

notifications:
  email:
    - sebastian.luna.valero@gmail.com

