
language: python

python:
  - "2.7"

before_install:
  - chmod +x setup-DEBs.sh
  - sudo ./setup-DEBs.sh

install:
  - chmod +x setup-DEBs.sh
  - sudo ./setup-CGAT.sh
  - source $HOME/CGAT/virtualenv-1.10.1/cgat-venv/bin/activate

script: 
  - nosetests -v tests/test_scripts.py

notifications:
  email:
    - sebastian.luna.valero@gmail.com

